version: '3.8'
services:
  mongodb:
    image: mongo:4.0.16-xenial
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    name: nest-db
