# Default values for backend-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

namespace: prod

image:
  repository: registry.digitalocean.com/anyaa/backend-api
  tag: 'latest'

containerPort: 3000

ingress:
  tld: prod.anyaa.io
  domain: api
  path: /

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

acme:
  email: thaer.abbas@anyaa.io

storage:
  endpoint: https://ams3.digitaloceanspaces.com
  space: anyaa-prod
  