apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  mongodb-url: >-
    bW9uZ29kYitzcnY6Ly9hZG1pbjpPZ1RSTWVESzJFS0k3cHd1QG15YmFza2V0LWRldi43ejgzei5tb25nb2RiLm5ldC9hbnlhYS1taWdyYXRpb24=
