apiVersion: v1
kind: Secret
metadata:
  name: unifonic
  namespace: prod
type: Opaque
data:
  app-id: QVBiMjQxNjQ2YjUxOTU0NzBiOGI3NWEzMzViNzg1MmE1ZA==
  token: >-
    ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKelpYSjJhV05sWDJsa0lqb2lRVkJpTWpReE5qUTJZalV4T1RVME56QmlPR0kzTldFek16VmlOemcxTW1FMVpDSjkuSzFRWmxTak02Qk5pR3hCOWxHY3dLVFpsOWZPV1l2WGFpTTFweVdWZXRVQQ==
