name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: backend-api
  TAG: ${{ github.sha }}

jobs:
  #Push to Digital Ocean private Registry
  CD:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            app:
              - 'src/**'
              - 'Dockerfile*'

      - name: Install doctl # install the doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build image
        if: steps.changes.outputs.app == 'true'
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:$TAG

      - name: Push image
        if: steps.changes.outputs.app == 'true'
        run: |
          doctl registry login
          docker tag $IMAGE_NAME registry.digitalocean.com/anyaa/$IMAGE_NAME:$TAG
          docker push registry.digitalocean.com/anyaa/$IMAGE_NAME:$TAG

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: anyaa-k8s

      - name: Upgrade deployment
        run: |
          helm upgrade --install --atomic --timeout 5m backend-api ./infra/ -f ./infra/values-dev.yaml \
          --set-string image.tag=${{ github.sha }} \
          --namespace dev --create-namespace \
          --set-string sha=${{ github.sha }}
