name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: backend-api

jobs:
  #Push to Digital Ocean private Registry
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            app:
              - 'src/**'
              - 'Dockerfile*'

      - name: Install doctl # install the doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build image
        if: steps.changes.outputs.src == 'true'
        run: docker build . --file Dockerfile.alpine --tag $IMAGE_NAME

      - name: push image to digitalocean
        if: steps.changes.outputs.src == 'true'
        run: |
          doctl registry login
          docker tag $IMAGE_NAME registry.digitalocean.com/anyaa/$IMAGE_NAME
          docker push registry.digitalocean.com/anyaa/$IMAGE_NAME

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: anyaa-k8s

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install --atomic --timeout 1m backend-api ./infra/ -f ./infra/values-dev.yaml \
          --namespace dev --create-namespace

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up kubectl
  #       uses: matootie/dokube@v1.4.0
  #       with:
  #         personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  #         clusterName: anyaa-k8s

  #     - name: Check path
  #       run: |
  #         echo $GITHUB_WORKSPACE
  #         pwd
  #         ls -la

  #     - name: Deploy to Kubernetes
  #       run: |
  #         helm upgrade --install --atomic --timeout 1m backend-api $GITHUB_WORKSPACE/infra/ -f $GITHUB_WORKSPACE/infra/values-dev.yaml \
  #         --namespace dev --create-namespace
